version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build:
      context: ./etl
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/etl_db"
    depends_on:
      - postgres

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data:




